export const SPORTS = [
  "Baseball",
  "Basketball",
  "Cheerleading",
  "Cross Country",
  "Football",
  "Golf",
  "Gymnastics",
  "Hockey",
  "Lacrosse",
  "Soccer",
  "Softball",
  "Swimming",
  "Tennis",
  "Track & Field",
  "Volleyball",
  "Wrestling",
  "Other",
] as const;
